version: '2'
services:
  db:
    image: mariadb:10.4.12
    container_name: work_scheduler_db
    volumes:
      #- /var/lib/mysql/django_scheduler:/var/lib/mysql/django_scheduler
      #- ./mariadb_data:/var/lib/mysql/django_scheduler
      #- ./mariadb/django_scheduler_init.sql:/docker-entrypoint-initdb.d/django_scheduler_init.sql  # init SQL
      - dbvolume:/var/lib/mysql/django_scheduler                          # data volume
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_USER=django
      - MYSQL_PASSWORD=django
      - MYSQL_DATABASE=django_scheduler
    command: mysqld --character-set-client=utf8mb4 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - app-nw
  django:
    container_name: work_scheduler
    image: qtooone/work_scheduler:v1
    build: ./Scheduler/
    depends_on:
      - db
    links:
      - db
    environment:
      APP_PATH:             $APP_PATH
      DJANGO_READ_ENV_FILE: "true"
      DJANGO_ENVIRONMENT:   "production"
    volumes:
      - ./Scheduler:/opt/apps/Scheduler
    expose:
      - 8000
    #ports:
    #  - "8000:8000"
    networks:
      - app-nw
    working_dir: $APP_PATH
    #command: sh -c 'python3 manage.py migrate && python3 manage.py runserver 0:8000'
    command: >
      sh -c '
      python3 manage.py makemigrations
      && python3 manage.py migrate
      && python3 manage.py loaddata init_users
      && gunicorn --bind 0:8000 Scheduler.wsgi
      '
  nginx:
    build: ./nginx/
    image: qtooone/work_scheduler_nginx:v1
    container_name: work_scheduler_nginx
    depends_on:
      - django
    links:
      - django
    expose:
      - 8800
    ports:
      - "8800:8800"
    volumes:
      - ./Scheduler/static:/var/www/static
    networks:
      - app-nw

volumes:
  dbvolume:
    driver_opts:
      type: none
      device: $PWD/mariadb/mariadb_data
      o: bind

networks:
  app-nw:
    driver: bridge
