# Generated by Django 2.2.5 on 2020-06-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkScheder', '0002_workschedule_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workschedule',
            old_name='uid',
            new_name='user',
        ),
    ]
