# Generated by Django 3.0.4 on 2020-06-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkScheder', '0003_auto_20200616_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
