"""
Django settings for Scheduler project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from .settings_common import *

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    # setting of django
    'django': {
        'handlers': ['console'],
        'level'   : 'INFO',
    },
    # setting of WorkScheder App
    'WorkScheder': {
        'handlers': ['console'],
        'level'   : 'DEBUG',
    },
    # setting of 'handlers'
    'handlers': {
        'console': {
            'level'   : 'DEBUG',
            'class'   : 'logging.StreamHandler',
            'formatter': 'dev'
        },
    },
    # setting of 'formatters'
    'formatters': {
        'dev': {
            'format': '\t'.join([
                '%(asctime)s',
                '[%(levelname)s]',
                '%(pathname)s(Line:%(lineno)d)',
                '%(message)s'
            ])
        },
    },
}
