# Generated by Django 2.2.5 on 2020-05-28 06:22

from django.db import migrations
from django.core.management import call_command

def load_account_fixture(apps, schema_editor):
    call_command('loaddata', 'accounts/fixtures/init_users.json', app_label='accounts')

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.RunPython(load_account_fixture),
    ]
