# Generated by Django 3.0.4 on 2020-06-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200617_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adjust_num',
            field=models.IntegerField(null=True, verbose_name='adjust number'),
        ),
    ]
