# Generated by Django 2.2.5 on 2020-06-19 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200619_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adjust_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='adjust number'),
        ),
    ]
